### PR TITLE
upgrade-script does not pass on quotation

### LINKED ISSUE #61: missing "create" in create-upgrade script
the `create-upgrade` script should call `bin/upgrade create` but only calls `bin/upgrade`

### PR DESCRIPTION
**Pull request by lukasgraf**
```sh
$ create-upgrade "demo upgrade"
> .../bin/upgrade demo upgrade --path /Users/jone/projects/my.teamraum.com/my.teamraum
usage: .../my.teamraum/bin/upgrade
       [-h] [--version] {touch,create} ...
.../bin/upgrade: error: argument command: invalid choice: 'demo' (choose from 'touch', 'create')
```

Closes #61

### CODE REVIEW

**Comment by lukasgraf** [comment]
@jone using `pipes.quote` to ensure the arguments to `bin/upgrade` are quoted as needed by the shell should do the trick here.

**Comment by jone** [comment]
@lukasgraf cool!
Could you rebase onto master? I've "fixed" the testing issues :wink:

**Comment by lukasgraf** [comment]
@jone rebased.

**Comment by jone** [comment]
Nice, thank you :+1:

**Comment by mbaechtold** [comment]
Cool, just curled it!

**Pull request merged**
