### PR TITLE
Plone5 support

### PR DESCRIPTION
**Pull request by jone**
Add support for Plone5.

bildschirmfoto 2017-06-07 um 17 22 27

### CODE REVIEW

**Comment by deiferni** [comment]
@jone could we make sure this lands? in the meantime based https://github.com/4teamwork/ftw.upgrade/pull/139 on top of it 😉 .

**Comment by jone** [comment]
@maethu `@@manage-upgrades` seems to work well with Plone 5. Shall we 🚢 it?

**Comment by maethu** [comment]
@jone 🚢 it!!!!!!!!!!!!!

**Comment by idgserpro** [comment]
Since in the classifiers we're already at 5.1:

https://github.com/4teamwork/ftw.upgrade/blob/466e7930ba67e639af6362218ea0dfb8ca7b049a/setup.py#L39

Would it be the case to update compatibility sections in documentation?

https://github.com/4teamwork/ftw.upgrade/tree/71e6f61f02b1b2ba98986c39ae602e8efdd1223e#compatibility

**Comment by mbaechtold** [comment]
@idgserpro, thanks for noting the outdated README. I have created an issue for this: https://github.com/4teamwork/ftw.upgrade/issues/176

**Comment by mbaechtold** [comment]
@idgserpro, we have updated the list of compatible Planes: https://github.com/4teamwork/ftw.upgrade/tree/cdcb2a44af7d541e08616b67678dcfe33121840f#compatibility

**Pull request merged**
