### PR TITLE
The plone_upgrade subcommand does not break on Python3

### LINKED ISSUE #202: Error running plone upgrade on Python3
```
$ ./bin/upgrade plone_upgrade -s Plone 
b'"Plone Site was already up to date."'
Traceback (most recent call last):
  File "./bin/upgrade", line 385, in <module>
    sys.exit(ftw.upgrade.command.main())
  File ".../src/ftw.upgrade/ftw/upgrade/command/__init__.py", line 200, in main
    UpgradeCommand()()
  File ".../src/ftw.upgrade/ftw/upgrade/command/__init__.py", line 173, in __call__
    args.func(args)
  File ".../src/ftw.upgrade/ftw/upgrade/command/jsonapi.py", line 130, in func_wrapper
    return func(args, requestor)
  File ".../src/ftw.upgrade/ftw/upgrade/command/jsonapi.py", line 139, in func_wrapper
    return func(*args, **kwargs)
  File ".../src/ftw.upgrade/ftw/upgrade/command/plone_upgrade.py", line 56, in plone_upgrade_command
    if not any([x in line for x in expected]):
  File ".../src/ftw.upgrade/ftw/upgrade/command/plone_upgrade.py", line 56, in <listcomp>
    if not any([x in line for x in expected]):
TypeError: a bytes-like object is required, not 'str'
```

### PR DESCRIPTION
**Pull request by ale-rt**
Fixes #202

### CODE REVIEW

**Comment by ale-rt** [comment]
CC @buchi @maethu

**Review by buchi — APPROVED** [review]
Thanks!

**Comment by ale-rt** [comment]
Thanks to you guys :)

**Comment by buchi** [comment]
@ale-rt FYI: I made a new release that includes your contributions.

**Pull request merged**
